### ISSUE TITLE
Helm chart / docker image not running

### ISSUE THREAD

**Issue by armintsys** [it-at-m/dave-backend#84]
The docker image available is not running and dies without notification.
Please provide documentation for the image and how to run it.
What are the dependencies?

For local development a docker compose file with all needed dependencies would be nice too.

**Comment by klml** [comment]
@armintsys 

> The docker image available is not running and dies without notification.

did you use the [helm chart](https://artifacthub.io/packages/helm/it-at-m/dave)? And please add in the environment (docker, vanilla K8S,..)

**Comment by klml** [comment]
@armintsys 

> For local development a docker compose file with all needed dependencies would be nice too.

Will https://github.com/it-at-m/dave-frontend/issues/139 be helpful?

**Comment by armintsys** [comment]
> @armintsys
> 
> > The docker image available is not running and dies without notification.
> 
> did you use the [helm chart](https://artifacthub.io/packages/helm/it-at-m/dave)? And please add in the environment (docker, vanilla K8S,..)

No - I was using docker images - https://github.com/it-at-m/dave-backend/pkgs/container/dave-backend
Did not try helm charts.

Developed my own docker compose file for needed dependencies. Started the application(s) from cmd line.

**Comment by klml** [comment]
@armintsys we created an minimal documnetation https://github.com/it-at-m/dave#installation-instructions does this work for you?

**Comment by armintsys** [comment]
Hey @klml - yes the docu looks pretty good and understandable. Thanks a lot!

**Comment by armintsys** [comment]
Docu added.
