### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by armintsys** [it-at-m/dave-backend#86]
Did you think about implementing multi tenancy right into DAVe or is this not a topic so far?

Enabling multi tenancy would also be possible of course deploying all modules in different K8s namespaces or even different clusters.

Just wanted to know how you think about this?

**Comment by martind260** [comment]
Well the city of munich doesnt need it right now, but we thought about it a bit and identified these high-level tasks to implement muliti-tenancy in DAVe:

-     Save configuration of tenant data in a separate file / tenant database table
-     Read out tenant data and configure data sources and connections
-     Enrich all requests with tenant information
-     Route each DB operation via the tenant using the correct connection (e.g. with spring's AbstractRoutingDataSource)
-     Configuration UI for tenant data (e.g. DB connections, client-specific settings (e.g. city districts), user-to-tenant assignment, etc)
-     Extend authentication by tenant id
-     Consider tenant-specific settings for display in the frontend and calculations in the backend

**Comment by klml** [comment]
@armintsys Since we as the city of Munich have no need for this, we will not implement it, but we are open to contributions

**Comment by armintsys** [comment]
@klml thats fine, there are different solutions possible which do not require code changes. I think one of them could be enough for now. Thanks for help anyways.
